# Generated by Django 3.1.4 on 2021-10-09 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_contact_password_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='password',
            name='login',
            field=models.CharField(default=123, max_length=200),
            preserve_default=False,
        ),
    ]
